### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by vnijs** [thomasp85/fiery#1]
Curious to see how this would work. Any examples?

I'm also interested in how this compares to opencpu and something like https://github.com/erikriverson/spyre

**Comment by thomasp85** [comment]
Way too early for examples :-) This is a spare-time project suffering over no current spare-time... I'll give you a heads up when it has any real functionality.

The development started rather spontaneously after some discussions with shiny devs and other with interest in more ambitious web apps powered by R. There might be similar projects out there that I need to have a look at before I invest more time in it.

My goal is to have a framework that is just as easy/comprehensible as shiny, but only for the server side, leaving developers free to choose their favourite javascript framework for the front-end (Ember, Angular, Backbone etc.). It will revolve around an auto-updating model for stateful apps (the linkedObject that is actually functioning now - have a look), and a powerful router that takes care of registering handlers and dispatching messages and requests from the client.

I have some projects down the line that will require this functionality, but while other projects (my PhD) have higher priority, I cannot invest too much in it...

**Comment by thomasp85** [comment]
Spare looks really cool, but is ultimately a solution to a different problem. Fiery should make it easy for people to create something like Spyre by handling all the middleware stuff...

**Comment by thomasp85** [comment]
OpenCPU, it seems, also has a different goal. It tries to make it easy for web apps to request R computations, instead of having a direct back-and-forth communication with an R session. Fiery is mostly intended for local running apps (like Spyre) right now, because that is my use case. I want to make web apps a viable alternative to native GUIs, more than I want to make R a competitor to Ruby (rails) or Python (Django) for powering large websites.

**Comment by vnijs** [comment]
Sounds really interesting! So is Ember likely to be the best fit with Fiery or could it just as easily be linked with React, Angular, etc. as well?

On a somewhat related note ... do you have any suggestions on how to setup a shiny GUI app so it could be easily extended but others? See thread here https://github.com/vnijs/radiant/issues/10

**Comment by thomasp85** [comment]
I'm eventually going to use it with ember, but Fiery will be completely agnostic to the front-end framework. As long as it can somehow work with websocket or http (which would be all frameworks I know of).

My take on adding extensibility to web apps through package extensions are heavily coloured by my own use cases. I have thought about how others could supply alternative algorithms that might solve the same job, thus producing the same type of output. This could be solved with extension developers registering functions by supplying a data structure that specifies the different parameter choices that should be available within the GUI. Adding completely new functionality is a whole different story, and not necessarily something worthwhile as it would likely provide a subpar integration with the rest of the app - just my 2 cents

**Comment by vnijs** [comment]
Fair point about ‘subpar integration’. We’ll see how it goes. 




Looking forward to seeing how Fiery progresses!
