### ISSUE TITLE
resolved() operates on futures rather than expressions

### ISSUE THREAD

**Issue by HenrikBengtsson** [thomasp85/fiery#1]
(from my [Twitter comment](https://twitter.com/henrikbengtsson/status/748611412147073024)):

In https://github.com/thomasp85/fiery/blob/master/R/FutureStack.R#L59, if `private$futures[[id]]` is a future (Future object created by `future()`) then I think

``` r
resolved(private$futures[[id]]$expr, timeout = 0.05)
```

should be

``` r
resolved(private$futures[[id]], timeout = 0.05)
```

because `resolved()` operates on a single future, a list or environment of them.

**Comment by thomasp85** [comment]
This is bad naming on my part. private$futures contains lists. Each list encapsulates a future, a `then` function etc. The future is stored in expr. I should probably rename to make it clearer

**Comment by HenrikBengtsson** [comment]
I see. Now it makes sense. Sorry about the noise.
