### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by lepennec** [thomasp85/fiery#14]
Dear Thomas,

when I try to install the latest CRAN version, the installation stops at the testing step as shown below. 
I'm using the latest fedora and I have try both "terminal" R 3.4.1 and rstudio. How can I help?

Erwan

    R version 3.4.1 (2017-06-30) -- "Single Candle"
    Copyright (C) 2017 The R Foundation for Statistical Computing
    Platform: x86_64-redhat-linux-gnu (64-bit)

    R is free software and comes with ABSOLUTELY NO WARRANTY.
    You are welcome to redistribute it under certain conditions.
    Type 'license()' or 'licence()' for distribution details.

    Natural language support but running in an English locale

    R is a collaborative project with many contributors.
    Type 'contributors()' for more information and
    'citation()' on how to cite R or R packages in publications.

    Type 'demo()' for some demos, 'help()' for on-line help, or
    'help.start()' for an HTML browser interface to help.
    Type 'q()' to quit R.

    > install.packages("fiery")
    Installing package into ‘/home/lepennec/R/x86_64-redhat-linux-gnu-library/3.4’
    (as ‘lib’ is unspecified)
    --- Please select a CRAN mirror for use in this session ---
    trying URL 'https://ftp.gwdg.de/pub/misc/cran/src/contrib/fiery_1.0.0.tar.gz'
    Content type 'application/octet-stream' length 45562 bytes (44 KB)
    ==================================================
    downloaded 44 KB

    * installing *source* package ‘fiery’ ...
    ** package ‘fiery’ successfully unpacked and MD5 sums checked
    ** R
    ** preparing package for lazy loading
    ** help
    *** installing help indices
      converting help for package ‘fiery’
        finding HTML links ... done
        Fire                                    html  
        event_doc                               html  
        fake_request                            html  
        fiery-package                           html  
        plugin_doc                              html  
    Rd warning: /tmp/Rtmp5rAFdd/R.INSTALL3a4d65823c9a/fiery/man/plugin_doc.Rd:25: missing file link ‘setRefClass’
    *** copying figures
    ** building package indices
    ** testing if installed package can be loaded

**Comment by thomasp85** [comment]
Strange. Can I get you to confirm that all dependencies are available?

**Comment by lepennec** [comment]
All the dependencies are here and the package is functional after I kill the installation process.

**Comment by thomasp85** [comment]
That is really strange - I have not had any problems with Linux otherwise, but I do not have access to a fedora system so I cannot confirm if this is a local problem on your end - do you have access to other fedora systems?

**Comment by lepennec** [comment]
I will try to investigate... Another symptom is after I use fiery I cannot quit cleanly R.

**Comment by thomasp85** [comment]
Can I get a `sessionInfo()` with `fiery` loaded?

**Comment by lepennec** [comment]
```

> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora 26 (Workstation Edition)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] fiery_1.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12     codetools_0.2-15 brotli_1.0       listenv_0.6.0   
 [5] future_1.6.0     digest_0.6.12    later_0.3.9002   assertthat_0.2.0
 [9] R6_2.2.2         jsonlite_1.5     stringi_1.1.5    uuid_0.1-2      
[13] xml2_1.1.1       webutils_0.6     urltools_1.6.0   reqres_0.2.0    
[17] tools_3.4.1      triebeard_0.3.0  httpuv_1.3.5     parallel_3.4.1  
[21] compiler_3.4.1   globals_0.10.2 

```

**Comment by thomasp85** [comment]
I get word from Twitter that others on fedora doesn't have any problems during installation. Have you updated all packages?

**Comment by lepennec** [comment]
Yes. I will try to find out what's going on on my laptop. Feel free to
close this issue.

**Comment by lepennec** [comment]
I've found the culprit: "later". I had a dev version from github reverting to the one from CRAN solves this issue.
