### ISSUE TITLE
where to start debugging for crashing sessions?

### ISSUE THREAD

**Issue by dpastoor** [thomasp85/fiery#15]
Playing around with the routr/fiery doc examples, and I'm successfully crashing as soon as I hit the hello/anything/ endpoint

![image](https://user-images.githubusercontent.com/3196313/29459801-68817856-83f3-11e7-843b-a64bb3a98c5f.png)

it _did_ work once, but then I pinged from localhost:8080 once and it crashed, and now on subsequent times it is crashing every time from http://127.0.0.1:8080/hello/mars/

I thought it might have been a port conflict so changed that but still no good.

**Comment by dpastoor** [comment]
this is all over the place - I changed the port, set to block = TRUE and now its working, I am more using this ticket as a discussion point if others also run into this problem - I wonder if it could also be something to do with rstudio interception magic - I know they do some serious voodoo in places.

**Comment by dpastoor** [comment]
Ok I think I've narrowed it somewhat to an issue with the nonblocking mode. when I keep block = TRUE it seems to behave, but when switching back to nonblocking the first time I curl/hit from webpage it crashes.

**Comment by thomasp85** [comment]
Then my best guess is that it has something to do with `later`. Are you using the CRAN version of that package?

**Comment by dpastoor** [comment]
yep my thoughts as well - I was on the CRAN version. I am checking on the tip from github right now to see if that fixes it, though having trouble compiling it - yay for windows.

**Comment by dpastoor** [comment]
Ok, on the development version of (0.4) of later the behavior persists.

**Comment by thomasp85** [comment]
Can you replicate this on another computer?

**Comment by dpastoor** [comment]
I will give it a try on both another windows computer and my MBP and see what happens.

**Comment by thomasp85** [comment]
Any update?

**Comment by thomasp85** [comment]
I'll close - If there is any development feel free to reopen
