### ISSUE TITLE
Colorize logger_console output

### ISSUE THREAD

**Issue by cpsievert** [thomasp85/fiery#25]
It'd be awesome if console output was colored sensibly based on `event`/`request$status` values -- perhaps via https://github.com/r-lib/crayon#readme

**Comment by thomasp85** [comment]
I’ve already considered this, but got away from it since there’s no support in RStudio for crayon AFAIK

**Comment by cpsievert** [comment]
Huh, works for me, but looks as though RStudio may/may-not have ANSI support https://github.com/r-lib/crayon/commit/b5221ab0246050dc687dc8b9964d5c44c947b265#diff-a97512f9c006b3c3c804312b97da5545R52

![screen shot 2017-10-17 at 1 43 10 pm](https://user-images.githubusercontent.com/1365941/31682980-30ec848a-b341-11e7-8303-e6c647d802f0.png)
