### ISSUE TITLE
Cannot set_logger of a cloned server 

### ISSUE THREAD

**Issue by cpsievert** [thomasp85/fiery#30]
```r
library(fiery)

server <- Fire$new()
server2 <- server$clone()
server2$set_logger(fiery::logger_console("{event}: {message}"))
```

```r
Error in private$logger <- logger : 
  cannot change value of locked binding for 'logger'
```

**Comment by thomasp85** [comment]
Hmm... This seems to be a bug in how R6 clones objects. It identifies all functions as methods and not only those that were part of the original class definition...

This can of course be solved in fiery be storing the logger in a list, but we should probably alert @wch about the issue...
