### ISSUE TITLE
Consider running on random port in tests

### ISSUE THREAD

**Issue by gaborcsardi** [thomasp85/fiery#35]
Otherwise one cannot run multiple test suites in parallel. Or test suites for multiple versions of fiery, like we do in revdepcheck.

**Comment by HenrikBengtsson** [comment]
I second this, I almost always get:
```
✔ fiery 1.1.0                            ── E: 1     | W: 0     | N: 1                                        
```
when testing in parallel.  At times, there is a random delay such that the "old" and "new" tests on fiery do not clash, but it is more frequently a fail than a pass by chance.  I need to manually rerun fiery in sequential mode by `revdep_add(packages = "fiery")` followed by `revdep_check()`.

PS. There's more background on this in https://github.com/r-lib/revdepcheck/issues/95

**Comment by HenrikBengtsson** [comment]
Bumping. Pls.

**Comment by HenrikBengtsson** [comment]
Thanks for doing this - I can confirm that fiery now passes revdep checks just fine.
