### ISSUE TITLE
Merge fiery with vue framework

### ISSUE THREAD

**Issue by vikram-rawat** [thomasp85/fiery#43]
I think it's time r have is own rest api framework. Merging it vue can get us somewhere close to it.

How can I  create a function which can setup a barebone project like

https://github.com/vikram-rawat/VueApp?files=1

So that l anybody can setup a base project

**Comment by vikram-rawat** [comment]
Let's create a function which can setup a barebone project like

https://github.com/vikram-rawat/VueApp?files=1

**Comment by thomasp85** [comment]
I fully support such frameworks but the ethos of fiery is to stay minimal and agnostic. I think it would be better to create a stand-alone plugin with vue helpers etc
