### ISSUE TITLE
Is there a way I can create Plotly graph in fiery

### ISSUE THREAD

**Issue by vikram-rawat** [thomasp85/fiery#44]
I want to get the plotly code generated through R plotly and serve it on an API may be as plain text and then consume it on front end. How's that possible

**Comment by thomasp85** [comment]
Can you provide a minimal code example of what you want to be able to do?

**Comment by jackparmer** [comment]
> I want to get the plotly code generated through R plotly and serve it on an API may be as plain text and then consume it on front end

Plotly wrote Dash for R ("DashR") for exactly this use case (DashR uses Fiery as its web server). Here's a basic example of what you're describing: [](https://dashr.plotly.com/layout)
