### ISSUE TITLE
Add option to run a non-blocking server?

### ISSUE THREAD

**Issue by jackparmer** [thomasp85/fiery#45]
We're considering DashR's eventual support inside Jupyter notebooks (DashR uses Fiery as its web server). Can Fiery run in a background process / thread, so that the Jupyter REPL isn't blocked?

(Sister issue for Dash for Julia ("Dash.Jl"): https://github.com/plotly/Dash.jl/issues/48)

**Comment by rpkyle** [comment]
> We're considering DashR's eventual support inside Jupyter notebooks (DashR uses Fiery as its web server). Can Fiery run in a background process / thread, so that the Jupyter REPL isn't blocked?
> 
> (Sister issue for Dash for Julia ("Dash.Jl"): [plotly/Dash.jl#48](https://github.com/plotly/Dash.jl/issues/48))

We already leverage Fiery's existing support for non-blocking functionality when calling `ignite`, so I think the current API currently allows what's required. I think this can be closed 🙂

**Comment by jackparmer** [comment]
Thanks Ryan :)
