### ISSUE TITLE
future::multiprocess is deprecated since long and soon to become defunct

### ISSUE THREAD

**Issue by HenrikBengtsson** [thomasp85/fiery#50]
Hi. The 'multiprocess' backend has been deprecated since future 1.20.0 (Oct 2020).  The **fiery** package [uses it in the code and mentions it in the docs](https://github.com/search?q=repo%3Athomasp85%2Ffiery%20multiprocess&type=code), e.g.

https://github.com/thomasp85/fiery/blob/da9c27fc301c0b922a598785108da02ac58fe657/R/FutureStack.R#L96-L104

Using it produces a deprecation warning:

```
Warning message:
Detected creation of a 'multiprocess' future. Strategy 'multiprocess' is deprecated in future (>= 1.20.0)
[2020-10-30]. Instead, explicitly specify either 'multisession' (recommended) or 'multicore'. Starting 
with future 1.31.0 [2023-01-31], 'multiprocess' is the same as 'sequential'.
```

But this soon become a defunct error.  When that happens, `R CMD check` on the **fiery** package will break:

```
* checking tests ... ERROR
  Running ‘testthat.R’
Running the tests in ‘tests/testthat.R’ failed.
Complete output:
  > library(testthat)
  > library(fiery)
  > 
  > test_check("fiery")
  
  [ FAIL 1 | WARN 0 | SKIP 1 | PASS 253 ]
  
  ══ Skipped tests ═══════════════════════════════════════════════════════════════
  • On CRAN (1)
  
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Error ('test-Fire.R:368'): futures can be added and called ──────────────────
  <defunctError/error/condition>
  Error: Detected creation of a 'multiprocess' future. Strategy 'multiprocess' is defunct in future (>= 1.20.0) [2020-10-30
]. Instead, explicitly specify either 'multisession' (recommended) or 'multicore'.
  Backtrace:
      ▆
   1. └─app$async(...) at test-Fire.R:368:4
   2.   └─private$ASYNC$add(substitute(expr), then, substituted = TRUE)
   3.     └─private$make_future(expr, then, ...)
   4.       ├─base::do.call(private$catcher, list(expr = expr, lazy = private$lazy))
   5.       └─future::multiprocess(...)
   6.         └─future (local) dfcn(msg = msg, package = .packageName)
   7.           └─base::.Defunct(...)
  
  [ FAIL 1 | WARN 0 | SKIP 1 | PASS 253 ]
  Error: Test failures
  Execution halted
```

Can you please fix?

PS. This one went under my revdepcheck radar, because it called `multiprocess()` directly.  Please avoid that and use the recommended `plan(...)` approach instead.  (It might be that we one day will replace all those backend functions with backend configuration objects with the same names)

**Comment by HenrikBengtsson** [comment]
Regarding `plan()`, you might want to do something like (non-verified):

```r
fiery_bg_process <- function(..., envir = parent.frame()) {
  oplan <- plan(multisession)
  on.exit(plan(oplan), add = TRUE)
  future(..., envir = envir)
}
```

and use it as:

```r
 AsyncStack <- R6Class('AsyncStack', 
   inherit = FutureStack, 
   private = list( 
     catcher = 'fiery_bg_process' 
   )
 ) 
```

Source: https://future.futureverse.org/reference/plan.html

**Comment by HenrikBengtsson** [comment]
Just a friendly reminder about this one

**Comment by HenrikBengtsson** [comment]
FYI, future 1.32.0 is now on CRAN making `multiprocess` is defunct. Your package will begin to produce check errors on CRAN any time soon, and you might get a request to update your package from the CRAN Team.

**Comment by thomasp85** [comment]
Hi @HenrikBengtsson , sorry for the late reply and thanks for your persistence on this. I'll see if I can work out a solution for fiery

**Comment by HenrikBengtsson** [comment]
I see fiery 1.2.0 fixing this is now on CRAN. Thx
